export enum GenreEnum {
  Action = 'Action',
  Adventure = 'Adventure',
  Anime = 'Anime',
  Comedy = 'Comedy',
  Crime = 'Crime',
  Drama = 'Drama',
  Espionage = 'Espionage',
  Family = 'Family',
  Fantasy = 'Fantasy',
  History = 'History',
  Horror = 'Horror',
  Legal = 'Legal',
  Medical = 'Medical',
  Music = 'Music',
  Mystery = 'Mystery',
  Romance = 'Romance',
  ScienceFiction = 'Science-Fiction',
  Sports = 'Sports',
  Supernatural = 'Supernatural',
  Thriller = 'Thriller',
  War = 'War',
  Western = 'Western',
}
